apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: nodeapp
      context: src/frontend
deploy:
  kubectl:
    manifests:
      - k8s-manifests/**.yaml
