---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodeapp
  name: nodeapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
  selector:
    app: nodeapp
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapp
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  strategy: {}
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: nodeapp
        imagePullPolicy: Never
        name: nodeapp
        ports:
        - containerPort: 8080
        resources: {}

